-- ============================================
-- MiniCAD Database Schema
-- ============================================


-- ============================================
-- 1. PROFILES
-- Stores information about authenticated users
-- ============================================

create table public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    full_name text not null,
    role text not null check (role in ('dispatcher', 'officer')),
    on_duty boolean not null default false,
    last_seen_at timestamptz,
    created_at timestamptz not null default now()
);


-- ============================================
-- 2. INCIDENTS
-- Stores all incidents created by dispatchers
-- ============================================

create table public.incidents (
    id bigint generated by default as identity primary key,
    caller_name text not null,
    caller_phone text not null,
    location text not null,
    incident_type text not null,
    priority text not null check (
        priority in ('low', 'medium', 'high')
    ),
    description text not null,
    status text not null default 'new'
        check (
            status in (
                'new',
                'dispatched',
                'claimed',
                'en_route',
                'on_scene',
                'resolved'
            )
        ),
    claimed_by uuid references public.profiles(id),
    created_by uuid not null references public.profiles(id),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


-- ============================================
-- 3. INCIDENT REPORTS
-- Stores the report submitted by an officer
-- after responding to an incident
-- ============================================

create table public.incident_reports (
    id bigint generated by default as identity primary key,
    incident_id bigint not null unique
        references public.incidents(id) on delete cascade,
    officer_id uuid not null
        references public.profiles(id),
    summary text not null,
    outcome text not null,
    resolved_at timestamptz not null default now(),
    created_at timestamptz not null default now()
);


-- ============================================
-- 4. PUSH TOKENS
-- Stores Expo push notification tokens
-- for officer devices
-- ============================================

create table public.push_tokens (
    id bigint generated by default as identity primary key,
    user_id uuid not null unique
        references public.profiles(id) on delete cascade,
    token text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


-- ============================================
-- 5. INDEXES
-- Helps frequently used incident queries
-- ============================================

create index incidents_status_idx
on public.incidents(status);

create index incidents_claimed_by_idx
on public.incidents(claimed_by);

create index incidents_created_at_idx
on public.incidents(created_at);


-- ============================================
-- 6. ENABLE ROW LEVEL SECURITY
-- ============================================

alter table public.profiles
enable row level security;

alter table public.incidents
enable row level security;

alter table public.incident_reports
enable row level security;

alter table public.push_tokens
enable row level security;


-- ============================================
-- 7. HELPER FUNCTION
-- Gets the role of the currently logged-in user
-- ============================================

create or replace function public.get_my_role()
returns text
language sql
security definer
set search_path = public
stable
as $$
    select role
    from public.profiles
    where id = auth.uid();
$$;


-- ============================================
-- 8. PROFILES POLICIES
-- ============================================

create policy "Users can view their own profile"
on public.profiles
for select
to authenticated
using (
    id = auth.uid()
);


create policy "Dispatchers can view profiles"
on public.profiles
for select
to authenticated
using (
    public.get_my_role() = 'dispatcher'
);


create policy "Users can update their own profile"
on public.profiles
for update
to authenticated
using (
    id = auth.uid()
)
with check (
    id = auth.uid()
);


-- ============================================
-- 9. INCIDENT POLICIES
-- ============================================

create policy "Dispatchers can view incidents"
on public.incidents
for select
to authenticated
using (
    public.get_my_role() = 'dispatcher'
);


create policy "Dispatchers can create incidents"
on public.incidents
for insert
to authenticated
with check (
    public.get_my_role() = 'dispatcher'
    and created_by = auth.uid()
);


create policy "Dispatchers can update incidents"
on public.incidents
for update
to authenticated
using (
    public.get_my_role() = 'dispatcher'
)
with check (
    public.get_my_role() = 'dispatcher'
);


create policy "Officers can view dispatched incidents"
on public.incidents
for select
to authenticated
using (
    public.get_my_role() = 'officer'
    and status in (
        'dispatched',
        'claimed',
        'en_route',
        'on_scene',
        'resolved'
    )
);


create policy "Officers can update claimed incidents"
on public.incidents
for update
to authenticated
using (
    public.get_my_role() = 'officer'
    and claimed_by = auth.uid()
)
with check (
    public.get_my_role() = 'officer'
    and claimed_by = auth.uid()
);


-- ============================================
-- 10. INCIDENT REPORT POLICIES
-- ============================================

create policy "Dispatchers can view reports"
on public.incident_reports
for select
to authenticated
using (
    public.get_my_role() = 'dispatcher'
);


create policy "Officers can create reports"
on public.incident_reports
for insert
to authenticated
with check (
    public.get_my_role() = 'officer'
    and officer_id = auth.uid()
);


create policy "Officers can view their own reports"
on public.incident_reports
for select
to authenticated
using (
    officer_id = auth.uid()
);


-- ============================================
-- 11. PUSH TOKEN POLICIES
-- ============================================

create policy "Users can manage their own push token"
on public.push_tokens
for all
to authenticated
using (
    user_id = auth.uid()
)
with check (
    user_id = auth.uid()
);

-- ============================================
-- 12. REALTIME
-- ============================================

alter publication supabase_realtime
add table public.profiles;

alter publication supabase_realtime
add table public.incidents;

alter publication supabase_realtime
add table public.incident_reports;

alter table public.incidents
replica identity full;